server:
  port: 8098

spring:
  application:
    name: rabbitmq-demo
  rabbitmq:
    host: 192.168.25.129
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    #  开启消息投递确认
    publisher-returns: true
    publisher-confirm-type: correlated
#    消息重试设置
#    listener:
#      simple:
#        retry:
#          enabled: true
#          max-attempts: 5
#          max-interval: 30000ms
#          initial-interval: 3000ms
#          multiplier: 2
#        default-requeue-rejected: false # 在消费者出现异常时是否丢弃该消息还是重新入队，true：重新入队，入队后在队首
#        acknowledge-mode: none