server:
  port: 10001

spring:
  application:
    name: eurake-server-demo

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka01:10001/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
#    hostname需要和defaultZone保持一致
    hostname: eureka01

